### PR TITLE
mdoc update, build number 20190606.1

### PR DESCRIPTION
**Pull request by XamarinDocsService**
mdoc update, build number 20190606.1

### CODE REVIEW

**Comment by v-alje** [comment]
Docs Build status updates of commit _[edea4b4](https://github.com/xamarin/apple-api-docs/pull/142/commits/edea4b439068c5d5df52c6becde10bf566415c83)_: 

:clock10: **Full build**: the average full build time is _67 min(s) 50 sec(s)_, this is based on the last _9_ build(s) for this repository.

 :warning: **This is a FULL build** due to a recent Docs Build service upgrade, normally no action is required on your part. In the result you find subsequent builds still performing full builds, please contact your repository admin to manually perform a full build on the 'master' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by v-alje** [comment]
Docs Build status updates of commit _[edea4b4](https://github.com/xamarin/apple-api-docs/pull/142/commits/edea4b439068c5d5df52c6becde10bf566415c83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[en/ARKit/ARConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARFaceTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARFaceTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARImageTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARImageTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARObjectScanningConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARObjectScanningConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/AROrientationTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/AROrientationTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARSCNViewDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARSCNViewDelegate.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARWorldTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARWorldTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAsset.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAsset.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetResourceLoadingRequest.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetResourceLoadingRequest.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriter.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetWriter.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriterInput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetWriterInput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSessionDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSessionDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSessionPromptStyle.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSessionPromptStyle.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureConnection.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureConnection.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDevice.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDevice.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceFormat.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDeviceFormat.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureMovieFileOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureMovieFileOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCapturePhoto.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCapturePhoto.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCapturePhotoOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCapturePhotoOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureVideoPreviewLayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureVideoPreviewLayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeyRequest.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeyRequest.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeySession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeySession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeySessionServerPlaybackContextOptions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeySessionServerPlaybackContextOptions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaCharacteristic.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaCharacteristic.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaCharacteristics.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaCharacteristics.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaSelectionGroup.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaSelectionGroup.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaSelectionOption.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaSelectionOption.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaType.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaType.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaTypes.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaTypes.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMetadata.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMetadata.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMetadataItem.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMetadataItem.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItem.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItem.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItemAccessLogEvent.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItemAccessLogEvent.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItemOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItemOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVSampleBufferDisplayLayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVSampleBufferDisplayLayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideo.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideo.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoCompositionInstruction.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoCompositionInstruction.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoCompositionLayerInstruction.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoCompositionLayerInstruction.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoFieldMode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoFieldMode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/IAVAudioSessionDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/IAVAudioSessionDelegate.xml) | :white_check_mark:Succeeded | |
[en/AudioUnit/AUAudioUnit.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AudioUnit/AUAudioUnit.xml) | :white_check_mark:Succeeded | |
[en/AudioUnit/AudioUnit.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AudioUnit/AudioUnit.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPBarButtonProviding_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPBarButtonProviding_Extensions.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPGridTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPGridTemplate.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPListTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPListTemplate.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPManeuver.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPManeuver.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPMapTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPMapTemplate.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C6%5Ca3fa375f-32c5-dc35-e51a-d763709e81cb%5CPullRequest%5C201906062156408365-142%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JzKF1UC1vmqIWPT%2BKFsoP5HS6ClObj8ZBstd3hAM8O8%3D&st=2019-06-06T23%3A14%3A57Z&se=2019-07-07T23%3A19%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-alje** [comment]
Docs Build status updates of commit _[f7ab40a](https://github.com/xamarin/apple-api-docs/pull/142/commits/f7ab40abe4089d7fa33a427b39b674116b4cc377)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[en/ARKit/ARConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARFaceTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARFaceTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARImageTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARImageTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARObjectScanningConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARObjectScanningConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/AROrientationTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/AROrientationTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARSCNViewDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARSCNViewDelegate.xml) | :white_check_mark:Succeeded | |
[en/ARKit/ARWorldTrackingConfiguration.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/ARKit/ARWorldTrackingConfiguration.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAsset.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAsset.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetResourceLoadingRequest.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetResourceLoadingRequest.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriter.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetWriter.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriterInput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAssetWriterInput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSessionDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSessionDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioSessionPromptStyle.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVAudioSessionPromptStyle.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureConnection.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureConnection.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDevice.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDevice.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceFormat.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDeviceFormat.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureMovieFileOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureMovieFileOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCapturePhoto.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCapturePhoto.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCapturePhotoOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCapturePhotoOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureVideoPreviewLayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVCaptureVideoPreviewLayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeyRequest.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeyRequest.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeySession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeySession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVContentKeySessionServerPlaybackContextOptions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVContentKeySessionServerPlaybackContextOptions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaCharacteristic.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaCharacteristic.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaCharacteristics.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaCharacteristics.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaSelectionGroup.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaSelectionGroup.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaSelectionOption.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaSelectionOption.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaType.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaType.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMediaTypes.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMediaTypes.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMetadata.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMetadata.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVMetadataItem.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVMetadataItem.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItem.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItem.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItemAccessLogEvent.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItemAccessLogEvent.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVPlayerItemOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVPlayerItemOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVSampleBufferDisplayLayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVSampleBufferDisplayLayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideo.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideo.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoCompositionInstruction.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoCompositionInstruction.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoCompositionLayerInstruction.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoCompositionLayerInstruction.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVVideoFieldMode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/AVVideoFieldMode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/IAVAudioSessionDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AVFoundation/IAVAudioSessionDelegate.xml) | :white_check_mark:Succeeded | |
[en/AudioUnit/AUAudioUnit.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AudioUnit/AUAudioUnit.xml) | :white_check_mark:Succeeded | |
[en/AudioUnit/AudioUnit.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/AudioUnit/AudioUnit.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPBarButtonProviding_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPBarButtonProviding_Extensions.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPGridTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPGridTemplate.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPListTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPListTemplate.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPManeuver.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPManeuver.xml) | :white_check_mark:Succeeded | |
[en/CarPlay/CPMapTemplate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190606.1/en/CarPlay/CPMapTemplate.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C15%5Ca3fa375f-32c5-dc35-e51a-d763709e81cb%5CPullRequest%5C201906150029018112-142%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ULTV2UJdCU3pzBkt49%2FXBpaFQXzJ7SsyWEjY1ruGL4E%3D&st=2019-06-15T01%3A59%3A57Z&se=2019-07-16T02%3A04%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
Supplanted by 20190619.1

**Pull request closed without merging**
