### PR TITLE
mdoc update, build number 20190619.1

### PR DESCRIPTION
**Pull request by XamarinDocsService**
mdoc update, build number 20190619.1

### CODE REVIEW

**Comment by v-alje** [comment]
Docs Build status updates of commit _[0bb7244](https://github.com/xamarin/apple-api-docs/pull/145/commits/0bb7244bf96c2518093474e37552e8b6d3e84216)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/_dependentPackages/ECMA2Yaml/tools/Run.ps1) | :x:Error | | [Details](#user-content-bd18f9f4-52050ba3)
[.openpublishing.publish.config.json](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-d902ab53-52050ba3)
[]() | :x:Error | | [Details](#user-content-52050ba3)

<a id="bd18f9f4-52050ba3"></a>
### [_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/_dependentPackages/ECMA2Yaml/tools/Run.ps1)
 - **Line 82**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Exit code: -1`````
 - **Line 218**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="d902ab53-52050ba3"></a>
### [.openpublishing.publish.config.json](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/.openpublishing.publish.config.json)
 - **Line 81**: **[Error]** `````Failed to execute customized script at step docset_prebuild in docset XamarinAppleAPI. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins for docset XamarinAppleAPI step docset_prebuild or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="52050ba3"></a>
###
 - **Line 138**: **[Error]** `````W:\syde-s\.optemp\packages\opbuild.scripts.1.76.0\tools\opbuild\docset.prebuild.ps1 failed to execute`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C19%5Ca3fa375f-32c5-dc35-e51a-d763709e81cb%5CPullRequest%5C201906192053080574-145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9q%2FjJWdemce42SaBVS9XzPdnaa8SMmHm0sbu8nkFkHQ%3D&st=2019-06-19T20%3A54%3A00Z&se=2019-07-20T20%3A59%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-alje** [comment]
Docs Build status updates of commit _[d767464](https://github.com/xamarin/apple-api-docs/pull/145/commits/d767464e47b9c11a8b05e3c4e35be369bc63396b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/_dependentPackages/ECMA2Yaml/tools/Run.ps1) | :x:Error | | [Details](#user-content-bd18f9f4-853ac330)
[.openpublishing.publish.config.json](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-d902ab53-853ac330)
[]() | :x:Error | | [Details](#user-content-853ac330)

<a id="bd18f9f4-853ac330"></a>
### [_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/_dependentPackages/ECMA2Yaml/tools/Run.ps1)
 - **Line 82**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Exit code: -1`````
 - **Line 218**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="d902ab53-853ac330"></a>
### [.openpublishing.publish.config.json](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/.openpublishing.publish.config.json)
 - **Line 81**: **[Error]** `````Failed to execute customized script at step docset_prebuild in docset XamarinAppleAPI. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins for docset XamarinAppleAPI step docset_prebuild or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="853ac330"></a>
###
 - **Line 138**: **[Error]** `````W:\ira5-s\.optemp\packages\opbuild.scripts.1.76.0\tools\opbuild\docset.prebuild.ps1 failed to execute`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C19%5Ca3fa375f-32c5-dc35-e51a-d763709e81cb%5CPullRequest%5C201906192100180045-145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LaPh807H5pwb2kx3s1EOSxq67pzb%2FqeyFenThs7uuKQ%3D&st=2019-06-19T21%3A01%3A12Z&se=2019-07-20T21%3A06%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-alje** [comment]
Docs Build status updates of commit _[a17189b](https://github.com/xamarin/apple-api-docs/pull/145/commits/a17189bdf7ad83d9f06649cb0a01d15e6ffdbe97)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by v-alje** [comment]
Docs Build status updates of commit _[a17189b](https://github.com/xamarin/apple-api-docs/pull/145/commits/a17189bdf7ad83d9f06649cb0a01d15e6ffdbe97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[en/api/XamarinAppleAPI/_splitted/CoreImage/toc.yml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/api/XamarinAppleAPI/_splitted/CoreImage/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/coreimage?branch=pr-en-us-145) | [Details](#user-content-448f7667-1d058d36)
[en/AVFoundation/AVAsset.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAsset.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetExportPresetApple.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetExportPresetApple.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetExportSession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetExportSession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetImageGenerator.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetImageGenerator.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetResourceLoadingRequest.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetResourceLoadingRequest.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetTrack.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetTrack.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriter.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetWriter.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAssetWriterInput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAssetWriterInput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAsynchronousKeyValueLoading.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAsynchronousKeyValueLoading.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioConverter.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioConverter.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioEngine.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioEngine.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioInputNode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioInputNode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioNode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioNode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioPlayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioPlayer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioPlayerDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioPlayerDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioPlayerDelegate_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioPlayerDelegate_Extensions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioPlayerNode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioPlayerNode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioRecorder.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioRecorder.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioRecorderDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioRecorderDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioRecorderDelegate_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioRecorderDelegate_Extensions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioTimePitchAlgorithm.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioTimePitchAlgorithm.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioUnit.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioUnit.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioUnitComponent.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioUnitComponent.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVAudioUnitComponentManager.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVAudioUnitComponentManager.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureAudioChannel.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureAudioChannel.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureAudioDataOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureAudioDataOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureAudioFileOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureAudioFileOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureAudioPreviewOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureAudioPreviewOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureConnection.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureConnection.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDataOutputSynchronizer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDataOutputSynchronizer.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDataOutputSynchronizerDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDataOutputSynchronizerDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDevice+Notifications.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDevice+Notifications.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDevice.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDevice.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceFormat.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDeviceFormat.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceInput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDeviceInput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceInputSource.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDeviceInputSource.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureDeviceTransportControlsPlaybackMode.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureFileOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureFileOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureFileOutputDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureFileOutputDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureFileOutputDelegate_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureFileOutputDelegate_Extensions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureFileOutputRecordingDelegate.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureFileOutputRecordingDelegate.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureFileOutputRecordingDelegate_Extensions.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureFileOutputRecordingDelegate_Extensions.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureMovieFileOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureMovieFileOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureScreenInput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureScreenInput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureSession.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureSession.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureStillImageOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureStillImageOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureVideoDataOutput.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureVideoDataOutput.xml) | :white_check_mark:Succeeded | |
[en/AVFoundation/AVCaptureVideoPreviewLayer.xml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/AVFoundation/AVCaptureVideoPreviewLayer.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a id="448f7667-1d058d36"></a>
### [en/api/XamarinAppleAPI/_splitted/CoreImage/toc.yml](https://github.com/xamarin/apple-api-docs/blob/PR-Update-20190619.1/en/api/XamarinAppleAPI/_splitted/CoreImage/toc.yml)
 - **[Warning]** `````Unable to find file with uid "CoreImage.CICMYKHalftone" referenced by TOC file "api/XamarinAppleAPI/_splitted/CoreImage/toc.yml"`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C25%5Ca3fa375f-32c5-dc35-e51a-d763709e81cb%5CPullRequest%5C201906242259467112-145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2b8OeuLjawuMoZHY8MtEv4KJVkccO9O%2BBWnKNJa1z%2BI%3D&st=2019-06-25T01%3A12%3A47Z&se=2019-07-26T01%3A17%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lobrien** [comment]
a) Dealing with CICMYKHalftone has been the responsibility of https://github.com/xamarin/doctools/blob/master/api-docs/RemoveRecursiveInheritance.fsx BUT I'm confident that doesn't deal with `toc.yml`, so this appears to be a new issue (or at least a new manifestation). 

b) Yes, this PR replaces PR 142.

**Comment by conceptdev** [comment]
I think I'd be OK to merge this with the warning, while we figure out why it suddenly appeared as a "TOC warning".

**Pull request merged**
